# Generated by Django 5.0 on 2023-12-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
