# Generated by Django 5.0 on 2024-01-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='Debit', max_length=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Fashion', 'Fashion'), ('Car', 'Car'), ('Bills', 'Bills'), ('Public Transport', 'Public Transport'), ('Property', 'Property'), ('Income', 'Income'), ('Investing', 'Investing'), ('Healthcare', 'Healthcare'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Savings', 'Savings'), ('Travel', 'Travel')], max_length=25),
        ),
    ]
