# Generated by Django 5.0 on 2024-01-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Fashion', 'Fashion'), ('Car', 'Car'), ('Bills', 'Bills'), ('Public Transport', 'Public Transport'), ('Housing', 'Housing'), ('Income', 'Income'), ('Investing', 'Investing'), ('Healthcare', 'Healthcare'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Savings', 'Savings'), ('Travel', 'Travel')], max_length=25),
        ),
    ]
